name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t jaredto2/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true jaredto2/docker-react npm test
